name: opencv-demo-ogra
version: '0.1'
base: core20
type: app
summary: A little face recognition test
description: |
  A simple OpenCV demo snap, shipping with three python based demos
    - opencv-demo-ogra.eyedetect - demo eye detection
    - opencv-demo-ogra.facedetect - demo face detection
    - opencv-demo-ogra.vidcapture - just a simple video capture demo
  please make sure to run
    sudo snap connect opencv-demo-ogra:camera
  to allow the demo to access your webcam

grade: stable
confinement: strict

apps:
  daemon:
    command: snap/command-chain/desktop-launch $SNAP/usr/local/bin/xwayland-kiosk-launch $SNAP/bin/eyedetect.py
    daemon: simple
    extensions: [ gnome-3-38 ]
    
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$SNAP/usr/lib/x86_64-linux-gnu/atlas/:$LD_LIBRARY_PATH
      XWAYLAND_FULLSCREEN_WINDOW_HINT: title="opencv-demo"
    slots: [ x11-slot ]
    plugs:
      - camera
      - home
     # - mir
      - network
      - network-bind
     # - opengl
     # - wayland
     # - x11-plug
  vidcapture:
    command: bin/vidcapture.py
    extensions: [ gnome-3-38 ]
    environment:
     # LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$LD_LIBRARY_PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$SNAP/usr/lib/x86_64-linux-gnu/atlas/:$LD_LIBRARY_PATH
      XWAYLAND_FULLSCREEN_WINDOW_HINT: title="opencv-demo"
    slots: [ x11-slot ]
    plugs:
      - camera
      - home
      #- opengl
      #- wayland
      #- x11-plug
  facedetect:
    command: bin/facedetect.py
    extensions: [ gnome-3-38 ]
    environment:
      #LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$LD_LIBRARY_PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$SNAP/usr/lib/x86_64-linux-gnu/atlas/:$LD_LIBRARY_PATH
      XWAYLAND_FULLSCREEN_WINDOW_HINT: title="opencv-demo"
    slots: [ x11-slot ]
    plugs:
      - camera
      - home
      #- opengl
      #- wayland
      #- x11-plug
  eyedetect:
    command: bin/eyedetect.py
    extensions: [ gnome-3-38 ]
    environment:
      #LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$LD_LIBRARY_PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$SNAP/usr/lib/x86_64-linux-gnu/atlas/:$LD_LIBRARY_PATH
      XWAYLAND_FULLSCREEN_WINDOW_HINT: title="opencv-demo"
    slots: [ x11-slot ]
    plugs:
      - camera
      - home
      #- opengl
      #- wayland
      #- x11-plug
  facetracker:
    command: usr/local/bin/facetracker
    extensions: [ gnome-3-38 ]
    environment:
      XWAYLAND_FULLSCREEN_WINDOW_HINT: title="opencv-demo"
    slots: [ x11-slot ]
    plugs:
      - camera
      - home
      #- opengl
      #- wayland
      #- x11-plug

plugs:
  x11-plug:
    interface: x11
slots:
  x11-slot:
    interface: x11
parts:
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv.git
    source-tag: 4.6.0
    cmake-parameters:
#    configflags:
      - -DINSTALL_C_EXAMPLES=ON
      - -DINSTALL_PYTHON_EXAMPLES=ON
      - -DBUILD_EXAMPLES=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DOPENCV_EXTRA_MODULES_PATH=contrib/modules
      - -DWITH_JASPER=ON
    after: [ xwayland-kiosk-helper ]
    override-build: |
      git clone https://github.com/opencv/opencv_contrib.git "$SNAPCRAFT_PART_BUILD"/contrib
      snapcraftctl build
    build-packages:
      - libjpeg-dev
      - libtiff5-dev
      - libpng-dev
      - libpng16-16 
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libatlas-base-dev
      - gfortran
      - python2.7-dev
      - python3-dev
    stage-packages:
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatlas3-base
      - libatspi2.0-0
      - libavcodec-extra58
      - libavformat58
      - libavutil56
      - libbluray2
      - libboost-filesystem1.67.0
      - libboost-system1.67.0
      - libcairo2
      - libcairo-gobject2
      - libcapnp-0.7.0
      - libdatrie1
      - libdc1394-22
      - libepoxy0
      - libexif12
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgl1-mesa-dri
      - libgme0
      - libgomp1
      - libgphoto2-6
      - libgphoto2-port12
      - libgraphite2-3
      - libgsm1
      - libharfbuzz0b
      - libicu66
      - libilmbase24
      - libjbig0
      - libjpeg-turbo8
      - libltdl7
      - libmirclient9
      - libmircommon7
      - libmircore1
      - libmirprotobuf3
      - libmodplug1
      - libmp3lame0
      - libogg0
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopenexr24
      - libopenjp2-7
      - libopus0
      - liborc-0.4-0
      - libpixman-1-0
      - libprotobuf-lite17
      - libpython2.7
      - libpython3.9
      - libraw1394-11
      - librtmp1
      - libschroedinger-coordgenlibs1
      - libschroedinger-maeparser1
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample3
      - libswscale5
      - libthai0
      - libtheora0
      - libtiff5
      - libtwolame0
      - libusb-1.0-0
      - libv4l-0
      - libv4lconvert0
      - libva2
      - libvo-aacenc0
      - libvo-amrwbenc0
      - libvorbis0a
      - libvorbisenc2
      - libvpx6
      - libwavpack1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libwebp6
      - libx11-6
      - libx264-155
      - libx265-179
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxvidcore4
      - libzvbi0
      - python-numpy
      - libtesseract4
      - to amd64: [ "libcrystalhd3:amd64", "libnuma1:amd64" ]
      - to i386: [ "libcrystalhd3:i386", "libnuma1:i386" ]
  xwayland-kiosk-helper:
    plugin: cmake
    source: xwayland-preload
    build-packages:
      - build-essential
    stage-packages:
      - xwayland
      - i3
      - libegl1-mesa
      - libgl1-mesa-glx
  demos:
    plugin: dump
    source: demos

  facetracker:
    after: [ opencv ]
    plugin: cmake
    source: https://github.com/alfonsosanchezbeato/Single_Face_Tracking_using_5_inbuilt_OpenCV_trackers.git
    source-tag: master
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/facetracker.cpp ${SNAPCRAFT_PART_SRC}/
      snapcraftctl build
  cleanup:
    after:
      - facetracker
    plugin: nil
    build-snaps:
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done  

